### ISSUE TITLE
Issue with get_tzone blowing up

### ISSUE THREAD

**Issue by jstrouse** [floraison/et-orbi#1]
I'm using Rails 2.3, rufus-scheduler 3.4, resque-scheduler 4.3, and tzinfo 0.3.53, et-orbi 1.0.3

When I start the scheduler, I'm getting

```
NoMethodError: undefined method `identifier' for nil:NilClass
.rvm/gems/ruby-2.3.3/gems/tzinfo-0.3.53/lib/tzinfo/timezone.rb:502:in `<=>'
.rvm/gems/ruby-2.3.3/gems/et-orbi-1.0.3/lib/et-orbi.rb:92:in `=='
```

What I'm finding is that I have a timezone set for the get_tzone function and it doesn't know how to respond to the == nil or the == :local from lines 92 and 93.

In order to make it work, I simply moved the return if you have a timezone above the nil and local check so it now looks like

```ruby
return o if o.is_a?(::TZInfo::Timezone)
return nil if o == nil
return local_tzone if o == :local
return ::TZInfo::Timezone.get('Zulu') if o == 'Z'
```

**Comment by jmettraux** [comment]
tzinfo 0.3.53: https://github.com/tzinfo/tzinfo/blob/015768f4a1656ced80af6183f093e6ba8dd15276/lib/tzinfo/timezone.rb#L501-L503
```ruby
    def <=>(tz)
      identifier <=> tz.identifier
    end
```

tzinfo 1.2.3: https://github.com/tzinfo/tzinfo/blob/02bcddd3ee748b4e9556335b3d714c7e1f459c77/lib/tzinfo/timezone.rb#L616-L619
```ruby
    def <=>(tz)
      return nil unless tz.is_a?(Timezone)
      identifier <=> tz.identifier
    end
```

An easy fix would be to recommend upgrading Timezone, but Rails here is a 2.x so that probably pins Timezone to this older version. Easier to fix that at the et-orbi level.

**Comment by jmettraux** [comment]
et-orbi 1.0.4, which includes this change, has been released https://rubygems.org/gems/et-orbi/versions/1.0.4

**Comment by jmettraux** [comment]
Thanks a lot!
